### DISCUSSION TITLE
How to include schema files for hip-cargo

### DISCUSSION THREAD

**Discussion by landmanbester** [caracal-pipeline/cult-cargo#94] [Ideas]
We've switched to creating the cabs definitions in packages like pfb-imaging and QuartiCal but we are still duplicating the schemas in cult-cargo. This is a bit of a nuisance from a maintenance perspective. Let's see if we can figure out a better way. @o-smirnov suggested a conditional `_include` mechanism

**Comment by o-smirnov** [comment]
https://github.com/caracal-pipeline/stimela/issues/374 is surely part of the solution. The schema (however it is distributed) would necessarily have to be selected based on the cab version. 

In principle this is just another twist on the ``dynamic_schema`` idea, but instead of just calling a Python function, we somehow go to an external data source to fetch the schema.

**Reply by o-smirnov** [reply]
Now as to how to store the schemas... Docker labels are tantalizing, but ChatGPT tells me singularity does not propagate them into its own images, which is kind of sad.

Another possible alternative is to include some logic for this in ``cargo-manifest.yml``. Something along the lines of "when you build this version of this image, also grab this file from this URL and place it *there*". So just spitballing a scenario here:

* build-cargo.py populates a subdirectory in the source tree, i.e. ``schemas/quartical/X.Y.Z/blahblah.yml``, as it processes the manifest.

* these schema files are added to git and checked in, and are also included in the cultcargo package

* The cab definition contains something like:

  ```yml
  cabs:
    quartical:
      load_schema: "(cultcargo)schemas/quartical/{self.version}/blahblah.yml"
  ```

* at construction time, the ``Cab`` object looks up the schema, and loads it up.

* When using the native backend, the user would have to specify

  ```yml
  cabs:
    quartical:
      load_schema: "(quartical)config/blahblah.yml"  # or whereever the schema lives
  ```
