### ISSUE TITLE
Stimela binds measurement set as read/write when write permissions are not required

### ISSUE THREAD

**Issue by talonmyburgh** [caracal-pipeline/cult-cargo#57]
For `stimela` recipes not requiring write access to the measurement set, `stimela` should load the measurement set in read-only mode.
An example error is seen below where `wsclean` is operating with flag `no-update-model-required` but stimela still attempts to open the measurement set in read/write and the process fails:
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/0e54790d-3c94-4d1f-986a-d30691e43ee3">

**Comment by talonmyburgh** [comment]
Yes but that should be fine - we don't need to write to the `ms`. If you run the `wsclean` command as is stipulated in the logs, it runs fine. `Stimela` unnecessarily tries to mount the `ms` as read/write.

**Comment by JSKenyon** [comment]
Yeah - I would expect the mounting to fail if `stimela` was at fault. The only alternative is if `wsclean` is actually inspecting the permissions on the mounted MS directory and deciding to use write locks based on that information. This should be easy enough to check if you mangle the `wsclean` cab to have `writable: false` in its definition of the MS.

**Comment by talonmyburgh** [comment]
See this comment by @o-smirnov https://chat.google.com/room/AAAAhSZnW6c/jA0EQsmI5kM/oGts36xb9R8?cls=10

**Comment by talonmyburgh** [comment]
It is read only, but `wsclean` does not require write permissions (as far as I know) when using the `no-update-model-required` in the args list above :)

**Comment by o-smirnov** [comment]
Yeah, it should be a simple fix, just a matter of getting the logic right. I think if (``-no-update-model-required`` is set OR ``-niter 0``) AND ``-predict`` is not set AND ``-store-imaging-weights`` is not set, then wsclean should not need to write to the MS. We could modify the dynamic schema easily.

But first @talonmyburgh, as per @JSKenyon's suggestion, could you try hardcoding ``writable: false`` [here](https://github.com/caracal-pipeline/cult-cargo/blob/master/cultcargo/genesis/wsclean/wsclean-base.yml#L7) and see if it runs for you?

**Comment by talonmyburgh** [comment]
Did not seem to work, changed the line, reinstalled `stimela` and `cult-cargo` but still get this error:
![image](https://github.com/user-attachments/assets/e3a24ff4-e365-4fcd-aca1-658a2028a84b)
Can confirm the quoted `wsclean` command works for version 2.10.1.

**Comment by o-smirnov** [comment]
OK so maybe it's a wsclean 3.3+ problem after all. Well, we can ask stimela to try the old one too. Can you add 

```
cab:
  wsclean:
    image:
      version: 2.10.1-cc0.1.2  # assuming your cult-cargo is 0.1.2?
```

to the top of your recipe (or options) and re-run?

**Comment by o-smirnov** [comment]
Add ``local-env.yml`` to your command-line?

**Comment by talonmyburgh** [comment]
Still not having luck... maybe I'm misunderstanding what I need to do. 
local-env.yml:
```
lib:
  misc:
    breifast:
      # common options for breifast cab can set en masse here
      cabs:
        # use virtual_env breifast for now
        wsclean:
          image:
            version: 2.10.1-cc0.1.3  # assuming your cult-cargo is 0.1.2?
        backend:
          select: native
```
gives:
```
$ stimela run breifast.recipes::tron.yml tron obs=47Tuc
2024-09-16 11:45:48 STIMELA INFO: starting                                                                               
2024-09-16 11:45:48 STIMELA INFO: loaded full configuration from cache                                                   
2024-09-16 11:45:48 STIMELA INFO: saving config dependencies to ./stimela.config.deps                                    
2024-09-16 11:45:48 STIMELA INFO: will load recipe/config file                                                           
/home/myburgh/venv/breifast_env/lib/python3.10/site-packages/breifast/recipes/tron.yml                                   
2024-09-16 11:45:48 STIMELA INFO: treating 'tron' as a recipe or cab name                                                
2024-09-16 11:45:50 STIMELA ERROR: error applying configuration from                                                     
/home/myburgh/venv/breifast_env/lib/python3.10/site-packages/breifast/recipes/tron.yml: Key 'wsclean' not in 'Cab'       
    full_key: cabs.breifast.stack-time-cube.wsclean                                                                      
    reference_type=Cab                                                                                                   
    object_type=Cab
```

**Comment by o-smirnov** [comment]
That's because wsclean is a top-level cab definition, it's not inside breifast. Add this to your local-env.yml:

```yml
cabs:
  wsclean:
    image:
      version: 2.10.1-cc0.1.3  # assuming your cult-cargo is 0.1.2?
```

**Comment by talonmyburgh** [comment]
Right sorry, my bad.
Can confirm that adding: 
```
cabs:
  wsclean:
    image:
      version: 2.10.1-cc0.1.3  # assuming your cult-cargo is 0.1.2?
```
to my `local-env.yml` and `no-update-model-required: true` to the `image-htc` step of  `breifast/breifast-tron/breifast/recipes` allows me to run `breifast` on a `measurement set` for which I have no `write` permissions.
