### ISSUE TITLE
mount empty ~/.casa for casa6 cabs

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/cult-cargo#65]
CASA6 (and older, possibly -- @bennahugo can you confirm?) looks for user configuration in ``~/.casa``.

This implies a potential unintended interaction with the user environment when running inside the container, compromising reproducibility.

The solution would be to mount an empty ``~/.casa`` when invoking the container (and possibly provide a runtime option to override this, for users that really do want to mount their own). This possibly needs an extra stimela feature, which would fit in well under the cab ``management`` section.

**Comment by o-smirnov** [comment]
Once https://github.com/caracal-pipeline/stimela/pull/378 is merged, this should be addressed by adding 

```yml
backend:
  singularity:
    bind_dirs:
      dot-casa:
        host: empty
        target: ~/.casa
```

to CASA cabs.
