### ISSUE TITLE
Request for an MS inspection tool as a cab

### ISSUE THREAD

**Issue by tmolteno** [caracal-pipeline/cult-cargo#84]
When debugging I often run into issues which require me to check the contents of a measurement set. For example I want to check for the existence of a MODEL_DATA table, or perhaps how much data is in there.  This happens in environments like k8, so running casa manually isn't possible or easy.

So, ideally I'd love to have an ms cab that is a bit of a ms inspector., to check some output. For example, in the following snippet, crystalball runs fine, but a following step says that MODEL_DATA doesn't exist, so putting the inspector in there would be very helpful.

```
        predict-model:
            cab: crystalball
            params:
                ms: =recipe.ms
                field: '{recipe.fluxcal}'
                sky-model: =recipe.fluxcal-sky-model
                num-sources: 50
                output-column: MODEL_DATA

        sanity-check:
            cab: inspector
            params:
                ms: =recipe.ms
                column: MODEL_DATA
```

Happy to write something, but hoping for ideas. We already have casa/listobs, but it would be nice to have something for more detailed diagnostics.
