### ISSUE TITLE
add FUSE support to casa6 images and unpack the AppImages

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/cult-cargo#91]
See recipe here: https://github.com/idia-astro/idia-container-casa-6/blob/master/casa-6-modular.def

Needed for plotms and such (@landmanbester).

**Comment by o-smirnov** [comment]
@landmanbester I've added this for plotms in the casa6 image. Have a go to see if it works for you now? Or just give me a simple test recipe?

**Comment by landmanbester** [comment]
I'm still getting
```
### running /usr/bin/singularity exec --pwd /home/bester/software/stimecipes --contain --bind                                                            
/home/bester/software/stimecipes:/home/bester/software/stimecipes:rw --bind /tmp/tmp87u8q0yn:/tmp:rw                                                     
/home/bester/.singularity/quay.io-stimela2-casa6:cc0.2.0.simg python3.10 -u -c ...                                                                       
# invoking callable casaplotms.plotms() using external interpreter                                                                                       
# /opt/casaplotms/usr/bin/casaplotms: error while loading shared libraries: libprofiler.so.0: cannot open shared object file: No such file or directory
```
Let me add the cab definition to cult-cargo then I'll send you a simple test recipe. Which branch should I use?

**Comment by o-smirnov** [comment]
``refactor-0.2.0`` please.

**Comment by landmanbester** [comment]
Different error
```
### running /usr/bin/singularity exec --pwd /home/bester/software/stimecipes --contain --bind                                                            
/home/bester/software/stimecipes:/home/bester/software/stimecipes:rw --bind /tmp/tmpvfqt4tdn:/tmp:rw                                                     
/home/bester/.singularity/quay.io-stimela2-casa6:cc0.2.0.simg python3.10 -u -c ...                                                                       
# invoking callable casaplotms.plotms() using external interpreter                                                                                       
# qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""                                                                                       
# This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.  
```

**Comment by landmanbester** [comment]
No, it shouldn't be trying to run interactively. Just save the result. This simple recipe reproduces the error
```yaml
_include:
  - (cultcargo.casa)plotms.yml

opts:
  log:
    dir: logs
    nest: 2
  backend:
    singularity:
      rebuild: false

plotit:
  inputs:
    ms:
      dtype: MS

  steps:
    goplot:
      cab: casa.plotms
      params:
        ms: =recipe.ms
        xaxis: frequency
        yaxis: amp
        correlation: XY,YX
        ydatacolumn: data
        coloraxis: corr
        avgbaseline: false
        uvrange: 1~400m
        plotfile: primary.short.raw.ampfreq.png
        showgui: false
        overwrite: True
```
It runs non-interactively with these params for pre-casa6 cabs

**Comment by o-smirnov** [comment]
Ugh this plugin business is a load of steaming turd. I got it to display this message:

root@3ef48d84facf:/# /opt/casaplotms/usr/bin/casaplotms 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: **Could not find the Qt platform plugin "xcb" in "/opt/casaplotms/usr/lib/plugins/platforms"**
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Available platform plugins are:** eglfs (from /opt/casaplotms/usr/lib/plugins/platforms), linuxfb (from /opt/casaplotms/usr/lib/plugins/platforms), minimal (from /opt/casaplotms/usr/lib/plugins/platforms), minimalegl (from /opt/casaplotms/usr/lib/plugins/platforms), offscreen (from /opt/casaplotms/usr/lib/plugins/platforms), vnc (from /opt/casaplotms/usr/lib/plugins/platforms), wayland-egl (from /opt/casaplotms/usr/lib/plugins/platforms), wayland (from /opt/casaplotms/usr/lib/plugins/platforms), wayland-xcomposite-egl (from /opt/casaplotms/usr/lib/plugins/platforms), wayland-xcomposite-glx (from /opt/casaplotms/usr/lib/plugins/platforms), **xcb (from /opt/casaplotms/usr/lib/plugins/platforms).**

Yes, thank you computer for being a moron.

**Comment by o-smirnov** [comment]
...hmmm but it seems to start under xvfb-run regardless. Had to change the cab definition as follows:

```yml
    _use: lib.misc.casa6.command-data
    flavour:
      kind: python
      interpreter_binary: xvfb-run -a python
```

The new error is 

```
# 2025-03-28 17:21:59   SEVERE  plotms::::casa  Task plotms raised an exception of class RuntimeError with the following message: callib file does not exist      
```

but that seems to do with how the parameter is passed? I notice it passes an empty string for ``callib``.
